// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwuMQOYvU-202QxpeKCeevFUzHhpKvgw',
    appId: '1:398065992407:web:85e079970dc48159f8e692',
    messagingSenderId: '398065992407',
    projectId: 'tenacity-tutoring-b8eb2',
    authDomain: 'tenacity-tutoring-b8eb2.firebaseapp.com',
    storageBucket: 'tenacity-tutoring-b8eb2.firebasestorage.app',
    measurementId: 'G-SN5M186MC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpaPKw8yHZ-LoYlJo4RGjxKi_p-ZOs2ic',
    appId: '1:398065992407:android:db66400b87de63acf8e692',
    messagingSenderId: '398065992407',
    projectId: 'tenacity-tutoring-b8eb2',
    storageBucket: 'tenacity-tutoring-b8eb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZ-wwO27iJh1NJCoTDCXOqlEIiqp8QFo',
    appId: '1:398065992407:ios:4276aa2d62e27350f8e692',
    messagingSenderId: '398065992407',
    projectId: 'tenacity-tutoring-b8eb2',
    storageBucket: 'tenacity-tutoring-b8eb2.firebasestorage.app',
    iosBundleId: 'com.example.tenacity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnZ-wwO27iJh1NJCoTDCXOqlEIiqp8QFo',
    appId: '1:398065992407:ios:4276aa2d62e27350f8e692',
    messagingSenderId: '398065992407',
    projectId: 'tenacity-tutoring-b8eb2',
    storageBucket: 'tenacity-tutoring-b8eb2.firebasestorage.app',
    iosBundleId: 'com.example.tenacity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPwuMQOYvU-202QxpeKCeevFUzHhpKvgw',
    appId: '1:398065992407:web:bde9f8135211e234f8e692',
    messagingSenderId: '398065992407',
    projectId: 'tenacity-tutoring-b8eb2',
    authDomain: 'tenacity-tutoring-b8eb2.firebaseapp.com',
    storageBucket: 'tenacity-tutoring-b8eb2.firebasestorage.app',
    measurementId: 'G-0JPL3CYPMW',
  );
}
