export * as auditApi from "./auditApi";
export * as attendanceApi from "./attendanceApi";
export * as classesApi from "./classesApi";
export * as enrolmentsApi from "./enrolmentsApi";
export * as invoicesApi from "./invoicesApi";
export * as reportsApi from "./reportsApi";
export * as studentsApi from "./studentsApi";
export * as termsApi from "./termsApi";
export * as usersApi from "./usersApi";
export * as waitlistApi from "./waitlistApi";
export * from "./callable";
export * from "./firestoreReads";
export * from "./storage";
