import React, { useEffect, useState } from "react";
import { deleteResourceJob, downloadResourceJob, listStudentResourceJobs } from "../../backend/resourcesApi";
import Badge from "../Badge";
import Button from "../Button";
import ConfirmDialog from "../ConfirmDialog";
import EmptyState from "../EmptyState";
import Table from "../Table";
import { useToast } from "../ToastProvider";
import { resourceLabel } from "./resourceTypes";

function capitalise(value) {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : "";
}

function formatDate(value) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleDateString();
}

function statusTone(status) {
  if (status === "complete") return "success";
  if (status === "failed") return "danger";
  if (status === "processing") return "info";
  return "neutral";
}

function warningSummary(row) {
  const warnings = Array.isArray(row?.warnings) ? row.warnings : [];
  if (!warnings.length) return "";
  return warnings[0]?.message || "An optional diagram was omitted.";
}

export default function StudentResourceHistory({ studentId }) {
  const toast = useToast();
  const [jobs, setJobs] = useState([]);
  const [busy, setBusy] = useState(true);
  const [deleteTarget, setDeleteTarget] = useState(null);
  const [deleting, setDeleting] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setBusy(true);
      setError("");
      try {
        const rows = await listStudentResourceJobs(studentId);
        if (!cancelled) setJobs(rows);
      } catch (loadError) {
        if (!cancelled) setError(loadError?.message || "Failed to load resource history.");
      } finally {
        if (!cancelled) setBusy(false);
      }
    }

    if (studentId) load();
    return () => { cancelled = true; };
  }, [studentId]);

  async function download(job) {
    try {
      await downloadResourceJob(job);
    } catch (downloadError) {
      toast.error("Download failed", downloadError?.message || "Could not fetch this resource.");
    }
  }

  async function deleteJob() {
    if (!deleteTarget || deleting) return;
    setDeleting(true);
    try {
      const jobId = deleteTarget.jobId || deleteTarget.id;
      await deleteResourceJob(jobId);
      setJobs((current) => current.filter((job) => (job.jobId || job.id) !== jobId));
      toast.success("Resource deleted", "The history item has been removed.");
      setDeleteTarget(null);
    } catch (deleteError) {
      toast.error("Delete failed", deleteError?.message || "Could not delete this resource.");
    } finally {
      setDeleting(false);
    }
  }

  if (busy) return <div className="route-inline-state">Loading resource history...</div>;

  if (error) {
    return (
      <div className="banner banner-danger">
        <div>
          <div className="banner-title">Could not load resources</div>
          <div>{error}</div>
        </div>
      </div>
    );
  }

  if (!jobs.length) {
    return <EmptyState icon="file-text" title="No resources yet">Generated resources for this student will appear here.</EmptyState>;
  }

  return (
    <>
      <Table
        columns={[
          { key: "date", header: "Date", render: (row) => formatDate(row.createdAtIso) },
          { key: "type", header: "Resource", render: (row) => resourceLabel(row.resourceType) },
          { key: "year", header: "Subject", render: (row) => `Year ${row.year || "-"} ${capitalise(row.subject)}` },
          { key: "createdBy", header: "Generated by", render: (row) => row.createdByName || "-" },
          {
            key: "status",
            header: "Status",
            render: (row) => {
              const warning = warningSummary(row);
              return (
                <div className="resource-status">
                  <Badge tone={statusTone(row.status)}>{row.status || "pending"}</Badge>
                  {warning ? <span className="resource-status-warning">{warning}</span> : null}
                </div>
              );
            },
          },
          {
            key: "actions",
            header: "",
            render: (row) => (
              <div className="row gap-2 wrap">
                {row.status === "complete" && row.outputPath ? (
                  <Button icon="download" onClick={(event) => { event.stopPropagation(); download(row); }} size="sm" variant="secondary">Download</Button>
                ) : null}
                {["complete", "failed"].includes(row.status) ? (
                  <Button
                    aria-label="Delete resource history item"
                    className="btn-icon rg-delete-action"
                    icon="trash"
                    onClick={(event) => { event.stopPropagation(); setDeleteTarget(row); }}
                    size="sm"
                    title="Delete"
                    variant="ghost"
                  />
                ) : null}
              </div>
            ),
          },
        ]}
        getRowKey={(row) => row.jobId || row.id}
        rows={jobs}
      />
      <ConfirmDialog
        busy={deleting}
        confirmLabel="Delete resource"
        message={
          deleteTarget
            ? `This removes ${resourceLabel(deleteTarget.resourceType)} from this student's resource history. Generated files and uploaded references for this job will also be removed where present.`
            : ""
        }
        onCancel={() => !deleting && setDeleteTarget(null)}
        onConfirm={deleteJob}
        open={Boolean(deleteTarget)}
        title="Delete resource history item"
      />
    </>
  );
}
