import React, { useEffect, useState } from "react";
import { downloadResourceJob, listStudentResourceJobs } from "../../backend/resourcesApi";
import Badge from "../Badge";
import Button from "../Button";
import EmptyState from "../EmptyState";
import Table from "../Table";
import { useToast } from "../ToastProvider";
import { resourceLabel } from "./resourceTypes";

function capitalise(value) {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : "";
}

function formatDate(value) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleDateString();
}

function statusTone(status) {
  if (status === "complete") return "success";
  if (status === "failed") return "danger";
  if (status === "processing") return "info";
  return "neutral";
}

export default function StudentResourceHistory({ studentId }) {
  const toast = useToast();
  const [jobs, setJobs] = useState([]);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setBusy(true);
      setError("");
      try {
        const rows = await listStudentResourceJobs(studentId);
        if (!cancelled) setJobs(rows);
      } catch (loadError) {
        if (!cancelled) setError(loadError?.message || "Failed to load resource history.");
      } finally {
        if (!cancelled) setBusy(false);
      }
    }

    if (studentId) load();
    return () => { cancelled = true; };
  }, [studentId]);

  async function download(job) {
    try {
      await downloadResourceJob(job);
    } catch (downloadError) {
      toast.error("Download failed", downloadError?.message || "Could not fetch this resource.");
    }
  }

  if (busy) return <div className="route-inline-state">Loading resource history...</div>;

  if (error) {
    return (
      <div className="banner banner-danger">
        <div>
          <div className="banner-title">Could not load resources</div>
          <div>{error}</div>
        </div>
      </div>
    );
  }

  if (!jobs.length) {
    return <EmptyState icon="file-text" title="No resources yet">Generated resources for this student will appear here.</EmptyState>;
  }

  return (
    <Table
      columns={[
        { key: "date", header: "Date", render: (row) => formatDate(row.createdAtIso) },
        { key: "type", header: "Resource", render: (row) => resourceLabel(row.resourceType) },
        { key: "year", header: "Subject", render: (row) => `Year ${row.year || "-"} ${capitalise(row.subject)}` },
        { key: "createdBy", header: "Generated by", render: (row) => row.createdByName || "-" },
        { key: "status", header: "Status", render: (row) => <Badge tone={statusTone(row.status)}>{row.status || "pending"}</Badge> },
        {
          key: "download",
          header: "",
          render: (row) => row.status === "complete" && row.outputPath
            ? <Button icon="download" onClick={(event) => { event.stopPropagation(); download(row); }} size="sm" variant="secondary">Download</Button>
            : "-",
        },
      ]}
      getRowKey={(row) => row.jobId || row.id}
      rows={jobs}
    />
  );
}
